WebSocket을 이용한 실시간 채팅 기능 구현
Attica-org/athens-backend pull request #37
Opened 2024-05-15 07:56 UTC by Starlight258

### 🔗 Linked Issue
- [ ] #21 

🛠 개발 기능

- `WebSocket`을 이용한 실시간 채팅 기능을 구현했습니다.
  - `Stomp` 프로토콜을 이용해 채팅을 전송하고, 전송한 채팅을 `DB`에 저장합니다.
  - 회원일 경우 `userName`, 비회원일 경우 `uuid`가 createdBy에 저장됩니다.

- WebSocket 연결 시 인증을 위해 `JwtChannelInterceptor`를 구현했습니다.
  - WebSocket 연결 시 `Authorization` 토큰을 검증하고 인증 객체를 설정합니다.

- 웹소켓 연결, 종료 시 `로그`를 출력하도록 했습니다.
- 개발 환경(dev/prod)에 따라 `CORS` 허용 origin을 다르게 설정했습니다.

🧩 해결 방법

- WebSocket 세션에 직접 접근할 수 없는 빈(`JpaConfig`)에서 사용할 수 있도록, 세션의 인증 정보를 `ThreadLocal`에 저장했습니다.
- 웹소켓 연결 시 인증을 위해 `JwtChannelInterceptor`를 구현하고 `WebSocketConfig`에 인터셉터를 등록했습니다.
- 개발 환경에 따라 CORS 허용 origin을 다르게 하기 위해 `@Value`로 환경 설정 값을 불러왔습니다.

🔍 리뷰 포인트

- `WebSocket`을 통한 실시간 채팅 기능이 정상적으로 동작하는지 확인 부탁드립니다.
  - 회원/비회원 구분, 인증, 메시지 전송 및 DB 저장 등
- `JwtChannelInterceptor`를 통한 `WebSocket 인증 로직`이 적절한지 피드백 부탁드립니다.
- `ThreadLocal`을 활용한 인증 정보 저장 및 사용 방식이 적절한지 검토 부탁드립니다.
- 개발 환경에 따른 `CORS 설정`이 잘 되어있는지 확인 부탁드립니다.

그 외 전반적인 개선사항이 있다면 말씀해주시면 감사하겠습니다 ㅎㅎ

코드 리뷰 부탁드려요~ 감사합니다! 😊

<br>

---
### 📋 Code Review Priority Guideline
- 🚨 **P1: Request Change**
  - **필수 반영**: 꼭 반영해주시고, 적극적으로 고려해주세요 (수용 혹은 토론).
- 💬 **P2: Comment**
  - **권장 반영**: 웬만하면 반영해주세요.
- 👍 **P3: Approve**
  - **선택 반영**: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다.

2024-05-15 19:12 UTC, yybmion requested changes
작업하느라 고생하셨습니다.

몇가지 코멘트 남기겠습니다.

2024-05-15 19:22 UTC, yybmion reviewed
고생많으셨습니다.

몇가지 코멘트 남기겠습니다.

2024-05-15 19:22 UTC, yybmion commented on src/main/java/com/attica/athens/global/interceptor/JwtChannelInterceptor.java
> +        jwtToken = jwtToken.substring(7);
7 은 "Bearer " 문자열의 길이를 나타내는데, '7' 이란 매직 넘버 대신 BEARER_.length()를 사용하면 어떨까요?

2024-05-15 19:22 UTC, yybmion commented on src/main/java/com/attica/athens/global/config/JpaConfig.java
검증 및 사용자 정보 가져오는 부분을 하나의 Optional 메소드로 묶는 것도 괜찮아보입니다.

예를 들어

```java
 private Optional<String> getAuthenticatedPrincipal() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {
            return Optional.empty();
        }

        Object principal = authentication.getPrincipal();
        if (principal instanceof CustomUserDetails) {
            return Optional.of(((CustomUserDetails) principal).getUsername());
        }

        return Optional.of(principal.toString());
    }
```

다음과 같이 Optional로 묶고 return 부분에서 

```java
return () -> Optional.ofNullable(getWebSocketUserId())
                .or(this::getAuthenticatedPrincipal)
                .orElseThrow(() -> new IllegalStateException("AuditorAware : principal is missing"));
```

만약 getWebSocketUserId가 null 반환하면 getAuthenticatedPrincipal 실행하고
두 방법 모두 실패 시 예외문구 출력하는 코드입니다.

2024-05-16 02:11 UTC, big-cir reviewed
고생하셨습니다.
코드를 직접 뜯어보면서 여러 방면에서 고민하신 부분들이 많으 느껴지네요.
궁금한 부분들에 대해서 질문 남겼습니다~~!

2024-05-16 02:11 UTC, big-cir commented on src/main/java/com/attica/athens/global/config/WebSocketConfig.java
> +    public void configureMessageBroker(MessageBrokerRegistry registry) {
taskscheduler를 설정할 때와 안 할 때의 차이가 있을까요?

2024-05-16 12:06 UTC, Starlight258 commented on src/main/java/com/attica/athens/global/config/JpaConfig.java
Optional을 이용해서 null 체크를 Optional 클래스에 위임하는 방법이네요! 
null 체크를 하는 코드가 사라져서 코드가 훨씬 깔끔하고 좋습니다 ! 👍 감사해요~
`getWebSocketUserId()`는 Optional을 반환하니 아래와 같이 작성해도 좋을 것 같아요.
```java
 @Bean
public AuditorAware<String> auditorAware() {
    return () -> getWebSocketUserId()
            .or(this::getPrinciple);
}
```

예외 처리는` getAuthenticatedPrincipal()`에서 던지는게 더 좋을 것 같다는 생각이 들어요, 에러 처리는 가능한 에러 발생한 곳 근처에서 해야 후에 에러 파악하기 쉽더라구요.
@yybmion님 덕분에 Optional에 대해 한번 더 생각해보게 되었어요~ 감사해요 😄

2024-05-16 12:41 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agoraUser/api/AgoraUserRepository.java
> +    Optional<AgoraUser> findByAgora_IdAndUser_Id(Long agoraId, Long userId);
_를 사용한 이유는 JPA의 쿼리 메서드에서 Agora라는 property 내부의 property를 접근할 때 _를 사용할 수 있기 때문입니다.
그런데 공식 문서를 찾아보니 `findByAgoraIdAndUserId` 라고 camel case로 사용해도 Agora 프로퍼티의 id에 접근할 수 있다고 해서 수정해보겠습니다! 

공식 문서
https://docs.spring.io/spring-data/jpa/reference/repositories/query-methods-details.html#repositories.query-methods.query-property-expressions

2024-05-16 14:44 UTC, Starlight258 commented on src/main/java/com/attica/athens/global/config/JpaConfig.java
> +        return Optional.ofNullable(WebSocketUtils.getSessionAttributes())
`redis`에 `websocket` 세션 정보를 저장하면 빠르게 접근할 수 있어서 그 부분은 고려하고 있어요!
구현한다면 `hash`에 세션 id를 key로 하고 인증 정보들을 value로 해서 저장할 예정이에요.

그런데 redis에 세션 정보를 저장한다면 redis는 보조 저장소이므로 정보가 사라질 수 있어서,
재인증 로직을 구현할 필요가 있어보여요.

2024-05-16 15:00 UTC, Starlight258 commented on src/main/java/com/attica/athens/global/config/WebSocketConfig.java
> +    public void configureMessageBroker(MessageBrokerRegistry registry) {
`taskscheduler` 기본 설정은 `heartbeat`(연결 확인) 10초 간격이고, `단일 스레드`로 동작하는 것으로 알고 있습니다. 성능이나 안정성 측면에서 `taskscheduler`는 따로 정의하는 것이 필요할 것 같아요. 
다음 pr에 웹소켓 세부 설정하여 올리겠습니다 !

2024-05-17 00:14 UTC, yybmion approved these changes
정말 고생많으셨습니다. 

덕분에 소켓과 관련된 많은 것들을 알게되었습니다!

2024-05-17 02:53 UTC, big-cir commented on src/main/java/com/attica/athens/domain/agoraUser/api/AgoraUserRepository.java
> +    Optional<AgoraUser> findByAgora_IdAndUser_Id(Long agoraId, Long userId);
보내주신 공식문서 확인해보니 camel case를 권장한다고 하네요!
snake case로도 프로퍼티 접근이 가능했는지 몰랐는데 감사합니다!

2024-05-17 02:56 UTC, big-cir commented on src/main/java/com/attica/athens/global/handler/WebSocketEventHandler.java
> +    }
확장을 고려하신 부분이 좋은 것 같습니다.
코드를 검토하면서 static 키워드에 관련해서 다시 한번 살펴보게 되었습니다. 👍🏻

2024-05-17 02:56 UTC, big-cir commented on src/main/java/com/attica/athens/domain/chat/dto/response/SendChatResponse.java
> +    }
nested record를 사용할 때 항상 타당한 근거를 제시하지 못했는데 답변 해주셔서 감사합니다.

2024-05-17 02:57 UTC, big-cir commented on src/main/java/com/attica/athens/global/config/JpaConfig.java
> +        return Optional.ofNullable(WebSocketUtils.getSessionAttributes())
추후 저희 서비스에는 어떻게 구현하는 것이 적합할지 trade off를 한 번 더 고민해 봐야겠네요. ㅎㅎ

2024-05-17 02:59 UTC, big-cir commented on src/main/java/com/attica/athens/global/config/WebSocketConfig.java
> +    public void configureMessageBroker(MessageBrokerRegistry registry) {
알려주셔서 감사합니다.
taskscheduler 설정 추가로 어떤 동작을 하는지 좀 더 공부해야겠습니다~!

2024-05-17 03:01 UTC, big-cir commented
여러 방면에서 신경쓰면서 구현 하시느라 고생하셨습니다. 👍🏻
작성해주신 코드 보면서 몰랐던 부분들을 추가적으로 공부할 수 있어서 좋았습니다.
감사합니다~

2024-05-17 03:02 UTC, big-cir approved these changes

2024-05-17 04:47 UTC, merged