투표하기 및 투표 결과 API / 아고라 title 단건 조회 및 아고라 ID 리스트 조회
Attica-org/athens-backend pull request #73
Opened 2024-06-02 17:48 UTC by yybmion

### 🔗 Linked Issue
- [ ] #64 
- [ ] #72 

resolved: #64 #72

### 🛠 개발 기능
- DEFAULT voteType에서 투표시 PROS,CONS 로 voteType 변경
- 아고라 id를 통해 voteType의  CONS,PROS 개수를 집계하여 결과로 응답
- 아고라 TITLE 단건 조회
- 아고라 ID 리스트 조회

### 🧩 해결 방법
- 따로 VOTE에 관한 DOMAIN을 만들지 않고 필드로 추가하여 불필요한 DOMAIN 설계를 하지 않음

### 🔍 리뷰 포인트
- 예외 처리 부분이 부족해 보이는데 발생할 수 있는 예외가 무엇이 있을지 확인 부탁드립니다.

<br>

---
### 📋 Code Review Priority Guideline
- 🚨 **P1: Request Change**
  - **필수 반영**: 꼭 반영해주시고, 적극적으로 고려해주세요 (수용 혹은 토론).
- 💬 **P2: Comment**
  - **권장 반영**: 웬만하면 반영해주세요.
- 👍 **P3: Approve**
  - **선택 반영**: 반영해도 좋고 넘어가도 좋습니다. 그냥 사소한 의견입니다.

2024-06-04 10:49 UTC, Starlight258 reviewed
고생하셨어요 👍

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
> +        AgoraIdResponse agoraIdList = agoraService.getAgoraIdList();
p2: 변수던 url 경로이던 이름에 특정 타입이나 구현 부분을 포함하면 좋지 않다고 생각해요.
후에 구현이 충분히 바뀔 수 있으므로 유연성 측면에서 ids로 수정하는 것 제안드려요 !
```suggestion
    @GetMapping("/ids")
    public ResponseEntity<ApiResponse<?>> getAgoraIds() {

        AgoraIdResponse agoraIds = agoraService.getAgoraIds();
```

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +                0L, 0L,
p1: 상수로 선언해서 값이 가진 의미를 분명하게 해주세요 !

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
p2:
- agora 조회하는 부분은 메서드로 분리해도 되겠네요~
- `AgoraTitleResponse`에 `Agora`만 인자로 넘겨도 충분하지 않을까요?

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/dao/AgoraQueryRepositoryImpl.java
> +
p2: 불필요한 줄바꿈이 들어가있네요 !

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/domain/Agora.java
> +    private Long consCount;
p2: 
- 투표 수는 Integer로 충분하지 않을까요?
- 따로 투표 테이블을 만들지 않았는데, 한 사람이 중복으로 투표할 경우는 어떻게 처리하는지 궁금합니다.

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
> +        return ResponseEntity.ok(ApiUtil.success(agoraVoteProsResponse));
p3: 이건 제가 작성한 코드에도 포함되는 건데, 저희 코드가 대체적으로 불필요한 변수 할당을 많이 하는 것 같아요.
`response`는 응답 만들때 한번 사용하는데 변수로 할당하고 있어요. 

이럴 경우에 코드의 응집도가 낮아져서 다른 사람이 개발했을때 코드의 로직에 위배되는 수정이 많아질 수 있다고 들었어요.
필요한 부분만 변수 할당을 하면 코드가 더 `간결`해지고 `흐름이 명확`해지는 장점도 있어요.

하지만 단점으로는 구현 과정에서 요구사항이 바뀌거나 수정해야할 부분이 있을 때 수정하기 어렵고, `중첩된 구조`가 자주 사용되어서 보기에 그리 좋아보이지 않을 수 있어요.

컨트롤러 부분이 대부분 `response`로 변수가 할당되어 작성되어있는데, 제안드린 부분은 사람마다 호불호가 갈리는 부분이라서 회의때 이야기해보면 좋을 것 같아요. 😃

만약 위와 같이 수정한다면 이런식이에요.
```java
return ResponseEntity.ok(
        ApiUtil.success(
            agoraVoteService.vote(userDetails.getUserId(),
                agoraVoteRequest, agoraId)
        )
    );
```

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
> +    @GetMapping("/{agora-id}/voteResult")
p2: [REST API 가이드](https://covenant.tistory.com/241) 읽어보시면 좋을 것 같아요!
```suggestion
    @GetMapping("/{agoraId}/results")
```

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
> +        agoraVoteRepository.updateVoteType(userId, agoraVoteRequest, agoraId);
p2: `service`의 `dto`가 `repository`까지 넘어가면 계층간 결합도가 증가하지 않을까요?

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepositoryImpl.java
> +                .where(agora.id.eq(agoraResult.getId()))
p2: `agoraResult`의 `id`만 사용한다면 `id`만 넘겨도 되지 않을까요?

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepositoryImpl.java
> +        return consResult.get(0);
p2:
```suggestion
        return consResult.isEmpty() ? 0L : consResult.get(0);
```

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/dto/response/AgoraVoteResultResponse.java
> +
p2: 불필요한 줄바꿈은 없는지 전체적으로 확인해주세요~

2024-06-04 10:49 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/exception/NotFoundUserException.java
> +public class NotFoundUserException extends CustomException {
👍

2024-06-04 11:06 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
> +    }
p2: @RequiredArgsConstructor를 사용해볼 수 있지 않을까요?

2024-06-04 11:09 UTC, Starlight258 commented
> ### 🔍 리뷰 포인트
> * 예외 처리 부분이 부족해 보이는데 발생할 수 있는 예외가 무엇이 있을지 확인 부탁드립니다.

아고라 상태가 `QUEUED`나 `RUNNING`일때 투표 요청이 오면 예외 처리가 필요할 것 같아요.

2024-06-04 12:50 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/api/AgoraOpenController.java
> +        AgoraIdResponse agoraIdList = agoraService.getAgoraIdList();
그렇군요 ! 팁 감사합니다 :)

2024-06-04 12:54 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +                0L, 0L,
상수로 선언하는 것을 깜빡했네요 감사합니다 👍

2024-06-04 13:00 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
분리하겠습니다! 

`agora status`는 dobby님 요구사항으로 추가했습니다 :)

2024-06-04 13:22 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/domain/Agora.java
> +    private Long consCount;
1. Integer로 변경했습니다.
2. 한 사람이 중복으로 투표를 할 수가있나요?? 그런 경우는 생각을 안했는데, 예를 들면 어떤 상황인거죠?

2024-06-04 13:31 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
> +        return ResponseEntity.ok(ApiUtil.success(agoraVoteProsResponse));
오호 확실히 각각의 장단점이 존재하는것 같군요. 

민트님이 말씀하신것처럼 저희 코드가 대부분 전자로 이루어져있어서 변경하려면 회의 때 이야기 해보는것이 좋을 것 같네요 👍

2024-06-04 13:45 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
> +        agoraVoteRepository.updateVoteType(userId, agoraVoteRequest, agoraId);
findByUserId의 결과값을 updateVoteType으로 넘기면 결합도가 증가한다는 의미가 맞나요??

맞다면 저도 처음에 결과값으로 넘겼었는데 생각해보니 하나의 userId에 대해 여러개의 agoraUser가 있을 수 있으니 List 형태로 반환하는데 이걸 넘길 바에는 그냥 Path Variable로 들어온 agoraId로 넘기는게 코드 짜기 편하다고 판단해서 대신 넘겼습니다!

2024-06-04 14:38 UTC, yybmion commented
말씀해주신 부분들 수정완료하였고

투표 API에서 AgoraStatus 가 `RUNNING` , `QUEDED` 일 경우 `InvalidAgoraStatusException` 에러를 발생시켰습니다!

귀중한 리뷰 감사합니다 @Starlight258

2024-06-05 05:30 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/api/AgoraAuthController.java
> +}
p1: 파일 끝에는 개행을 추가해주세요!
[No newline at a end of file](https://seongwon.dev/Git/20220303-%ED%8C%8C%EC%9D%BC%EC%9D%98_%EB%A7%88%EC%A7%80%EB%A7%89_%EA%B0%9C%ED%96%89/)
![image](https://github.com/Attica-org/athens-backend/assets/78211281/d0c63d4c-e5e4-48bd-8d65-eeab860f5b08)

2024-06-05 05:33 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
@yybmion 두번째에 제안드린 부분은 agora만 dto로 넘겨도 충분하지 않을지에 대한 이야기였어요~
```suggestion
        return new AgoraTitleResponse(agora);
```

2024-06-05 05:34 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/domain/Agora.java
> +    private Long consCount;
예를 들면 한 유저가 찬성 투표 요청을 두번 보낸 상황이라면, 투표수가 +1이 아닌 +2가 되지 않을지 궁금했어요~

2024-06-05 05:35 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
> +        return ResponseEntity.ok(ApiUtil.success(agoraVoteProsResponse));
넵 목요일에 이야기해봅시당 :)

2024-06-05 05:42 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
> +        agoraVoteRepository.updateVoteType(userId, agoraVoteRequest, agoraId);
제가 이야기 드린 부분은 `agoraVoteRequest`가 `서비스`의 dto인데 다른 계층인 `레포지토리`에 **인자로 전달하는게 좋은 방법인지** 에 대한 부분이에요.

`agoraVoteRepository.updateVoteType` 메서드를 보니, `agoraVoteRequest`의 `voteType()`만 사용하는데, `voteType`만 인자로 넘기는게 어떨까요? 

필요한 부분만 인자로 넘기는게 좋을 것 같아 제안드렸어요. 😃
`findByUserId`까지 코멘트 범위로 지정하여 헷갈리게 만들게 했네요 미안해요..😣

2024-06-05 05:45 UTC, Starlight258 requested changes
@yybmion 피드백 꼼꼼하게 반영해주셨네요 😀
eol 에러 수정후에 태깅해주시면 바로 approve하겠습니다 ! 
고생하셨어요~ 👍

2024-06-05 06:13 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
그렇군요! 근데 제가 AgoraTitleResponse에 String title, AgoraStatus status 이 2가지 인자를 응답하려고 하는데 agora만 넘겨도 되나요??

2024-06-05 06:14 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/domain/Agora.java
> +    private Long consCount;
제가 알기론 dobby님이 15초 투표하는 동안 마지막 값을 api로 요청하는 것으로 알고 있어서 그 부분은 문제 없을 듯 싶지만 한번 다시 여쭤보겠습니다!

2024-06-05 06:22 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/vote/application/AgoraVoteService.java
> +        agoraVoteRepository.updateVoteType(userId, agoraVoteRequest, agoraId);
아하 그렇군요 생각해보니 **서비스** `dto`가 `repository`까지 전달되면 좋은 방법인것 같지 않네요!

```java
agoraVoteRepository.updateVoteType(userId, agoraVoteRequest.voteType(), agoraId);
```
다음과 같이 `voteType()`만 전달했습니다. 감사합니다.

2024-06-05 07:05 UTC, yybmion commented
말씀해주신 부분 수정했습니다 👍 
@Starlight258

2024-06-05 07:57 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
agora를 넘기고 dto안에서 해당 속성을 `getter`로 가져오면 되지 않을까요?

제가 아래 댓글에서는 필요한 데이터만 전달하는 것에 대해 제안을 드려서 조금 헷갈리실 것 같아 정리하겠습니다.
- `service`에서 `repository`로 서비스에서 사용하는 dto를 전달하는 것은 계층간의 결합도가 높아질 수 있습니다.
   필요한 데이터만 전달하면 좋지 않을까요?

- dto를 생성할때에는 객체를 바로 넘기는 것이 개인적으로 더 좋은 것 같아요.
  dto 구조가 변경될 수 있으므로 객체만 전달하면 변경점이 줄어들고, dto는 내부 구조가 노출되어있으므로 결합도를 크게 신경쓰지 않아도 될 것 같아요 ([디미터 법칙](https://dkswnkk.tistory.com/687)도 dto에는 적용되지 않기 때문이에요)
  
  개인적인 의견이라 @yybmion 의 의견도 들어보고 싶네요!

2024-06-05 08:02 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/domain/Agora.java
> +    private Long consCount;
넵 프론트에서 한번만 요청되도록 제한을 두었다고 해도, 다른 방식으로 우회해서 서버에 요청을 보내거나 예외 상황이 발생할 수 있으므로 서버는 검증되지 않은 모든 요청에 대해 대비하고 있어야 해요.

2024-06-05 08:06 UTC, Starlight258 approved these changes
고생하셨습니다 👍

2024-06-05 09:53 UTC, yybmion commented
@big-cir 
배포 이슈로 먼저 Merge 하겠습니다 !
댓글 작성하시면 그 이후에 다음 PR에 반영해서 올리겠습니다. 

감사합니다 👍

2024-06-05 09:54 UTC, merged

2024-06-05 15:06 UTC, big-cir commented on src/main/java/com/attica/athens/domain/agora/vote/api/AgoraVoteController.java
> +    @GetMapping("/{agora-id}/voteResult")
현재 API들이 대부분 path variable인데, 카멜 케이스가 맞지 않나요?

2024-06-05 15:19 UTC, big-cir reviewed
리뷰가 늦어서 죄송합니다~
추가적으로 리뷰 남겼습니다~

2024-06-05 15:19 UTC, big-cir commented on src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepositoryImpl.java
> +public class AgoraVoteRepositoryImpl implements AgoraVoteRepository {
p1: 
동적 쿼리를 처리하는 클래스는 땡떙Query땡떙으로 네이밍 하고 있습니다.

2024-06-05 15:19 UTC, big-cir commented on src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepositoryImpl.java
> +    }
직접적으로 entitymanger를 컨트롤하는 이유가 있나요?

2024-06-05 18:32 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
민트님이 보내주신 `디미터 법칙` 정말 잘 읽었습니다.

이에 대해 질문이 있어 올립니다.

`디미터법칙` 은 객체가 또 다른 객체에 대해 지나치게 많은 정보를 가지고 있다는 것이 문제였는데 이를 해소시키기 위해 나왔고, 최소한의 .dot을 이용하고 함수를 통해 공개하게 만든다는 것이 핵심이라고 정리할 수 있겠네요. 

앞서 민트님이 말씀하셨다시피 dto는 예외사항으로 내부구조를 외부에 노출하는 것이 당연하여 `디미터법칙`이 적용되지 않는다고 나왔는데, 때문에 그런진 몰라도 지금 해당 문제가 `디미터법칙`과 크게 관련되어 있는게 맞나? 라고 생각이 드네요. 

물론 민트님이 말씀해주신 dto 변경이 일어난다면 만약 service에서 get을 쓰면 변경이 일어나 유지보수가 어려워진다는 단점에는 공감이 갑니다. 따라서 agora 자체를 넘겨주고 dto에서 getter을 통해 관리하면 이후 변경점이 있더라도 dto 부분만 변경하면 된다는 것입니다.

음,,,, 적다 보니 혼란이 와서 이후의 얘기는 좀 더 민트님과 나눠보겠습니다.

결론은 지금 이 문제가 `디미터법칙`이 맞는것인가? 입니다. 

좋은 자료 감사합니다 👍 @Starlight258

2024-06-06 03:48 UTC, Starlight258 commented on src/main/java/com/attica/athens/domain/agora/application/AgoraService.java
> +        return new AgoraTitleResponse(agora.getTitle(), agora.getStatus());
dto는 디미터 법칙 예외상황인데 제가 괜히 언급해서 헷갈리게 한 것 같네요..! 
오히려 수정하기 전이 디미터 법칙에는 맞는데, dto라 관련이 없는겁니닷

dto에 agora를 넘기면 dto의 내부 구조가 바뀌어도 변경점이 줄어든다.
dto는 결합도가 있을수밖에 없다. 
이 이야기를 하고싶었어요!

2024-06-06 03:54 UTC, yybmion commented on src/main/java/com/attica/athens/domain/agora/vote/dao/AgoraVoteRepositoryImpl.java
> +    }
말씀해주신 Dirty checking을 활용하여 JPA답게 설계해보도록 하겠습니다. 

감사합니다 👍